server:
  port: 8500

spring:
  application:
    name: small-fegin

#配置日志
logging:
  #配置日志文件路径
  path: G:\Project\mycloud\small-zuul-8080\src\log
  level:
    root: debug

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: small
    prefer-ip-address: true


zuul:
  #ignored-services: microservicecloud-dept
  prefix: /small
  ignored-services: "*"
  routes:
    small:
      serviceId: small-backstage
      path: /backstage/**

small-backstage: #是serviceId
  ribbon:
    listOfServers: http://localhost:8001 ,http://localhost:8002



