server:
  port: 8002

#配置日志
logging:
  #配置日志文件路径
  path: G:\Project\mycloud\small-backstage-8002\log
  level:
    root: debug

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    instance:
        instance-id: small-backstage-8002
        prefer-ip-address: true     #访问路径可以显示IP地址


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: cn.du.po    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
     name: small-backstage
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
     driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
     url: jdbc:mysql://localhost:3306/pinyougoudb             # 数据库名称
     username: root
     password: root
     dbcp2:
       min-idle: 5                                           # 数据库连接池的最小维持连接数
       initial-size: 5                                       # 初始化连接数
       max-total: 5                                          # 最大连接数
       max-wait-millis: 200

feign:
  hystrix:
    enabled: true
